# Generated by Django 5.2.7 on 2025-11-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logistic_Task', '0003_topic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
    ]
