# Generated by Django 5.2.7 on 2025-11-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistic_Task', '0007_alter_course_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text_task',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
    ]
