# Generated by Django 5.2.7 on 2025-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistic_Task', '0008_alter_task_text_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
