# Generated by Django 5.2.7 on 2025-11-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logistic_Task', '0009_alter_topic_options_topic_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='order',
        ),
    ]
