# Generated by Django 5.2.7 on 2025-11-09 19:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logistic_Task', '0010_alter_topic_options_remove_topic_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text_task',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
