# Generated by Django 5.2.7 on 2026-03-10 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistic_Task', '0011_alter_task_text_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AddField(
            model_name='task',
            name='expected_output',
            field=models.TextField(blank=True, null=True, verbose_name='Ожидаемый вывод'),
        ),
        migrations.AddField(
            model_name='task',
            name='initial_code',
            field=models.TextField(blank=True, default='# Напишите ваш код здесь\n', verbose_name='Начальный код'),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(blank=True, to='Logistic_Task.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='Logistic_Task.task'),
        ),
        migrations.CreateModel(
            name='UserTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, verbose_name='Последний код пользователя')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='Logistic_Task.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс по заданию',
                'verbose_name_plural': 'Прогресс по заданиям',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
