# Generated by Django 5.2.7 on 2026-03-12 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practikum', '0002_achievement_contest_submission_codereview_testcase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='codereview',
            options={'verbose_name': 'Код-ревью', 'verbose_name_plural': 'Код-ревью'},
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AlterModelOptions(
            name='contestscore',
            options={'verbose_name': 'Результат соревнования', 'verbose_name_plural': 'Результаты соревнования'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Количество учащихся'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Решение', 'verbose_name_plural': 'Решения'},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': 'Тест-кейс', 'verbose_name_plural': 'Тест-кейсы'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': 'Достижение пользователя', 'verbose_name_plural': 'Достижения пользователей'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(help_text='Например: solved_count или streak', max_length=50, verbose_name='Тип условия'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_value',
            field=models.IntegerField(default=1, verbose_name='Значение условия'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='🏆', max_length=10, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий'),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='practikum.submission', verbose_name='Решение'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('type', models.CharField(choices=[('task', 'За задачу'), ('first_try', 'Бонус за первую попытку'), ('achievement', 'За достижение'), ('contest', 'За соревнование')], max_length=20, verbose_name='Тип')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
            },
        ),
    ]
