# Generated by Django 5.2.8 on 2025-11-06 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practikum', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='group', max_length=30),
        ),
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practikum.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practikum.student')),
            ],
            options={
                'unique_together': {('student', 'group')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(through='practikum.Enrollment', to='practikum.student'),
        ),
    ]
