# Generated by Django 5.2.8 on 2025-11-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practikum', '0004_student_remove_group_group_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Имя', max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Фамилия', max_length=30, verbose_name='Фамилия'),
        ),
    ]
