# Generated by Django 5.2.8 on 2025-11-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practikum', '0005_remove_student_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
    ]
