# Generated by Django 5.2.7 on 2025-11-06 13:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practikum', '0007_alter_group_options_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Телефон'),
        ),
    ]
