server {
    listen 80;
    server_name practicumd.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name practicumd.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/practicumd.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/practicumd.duckdns.org/privkey.pem;

    location /static/js/sw.js {
        alias /app/staticfiles/js/sw.js;
        add_header Service-Worker-Allowed "/";
        add_header Cache-Control "no-cache";
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        resolver 127.0.0.11 valid=30s;
        set $upstream web:8000;
        proxy_pass http://$upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
